site_name: BTBillyBass
site_description: Arduino Animatronic Control System
site_url: https://example.com
repo_url: 
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
nav:
  - Home: index.md
  - Quick Start: QUICK_START.md
  - Hardware Setup: HARDWARE_SETUP.md
  - Commands: COMMANDS.md
  - API Reference: API.md
  - Troubleshooting: TROUBLESHOOTING.md
  - Changelog: CHANGELOG.md
  - Monorepo:
    - Merge Guide: MERGE_GUIDE.md
docs_dir: docs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
extra:
  social: []